name: WzWStuff
version: '${version}'

main: uk.firedev.wzwstuff.WzWStuff
api-version: '1.21.11'
load: POSTWORLD

authors: [ FireML ]

dependencies:
  server:
    DaisyLib:
      load: BEFORE
      required: true
    GriefPrevention:
      load: BEFORE
      required: true
